env:
  global:
    - CC_TEST_REPORTER_ID=9c3c9d52ed7edabf1e074b43f690dcba38c5872ad61ff4438fab675b4ca7e559

language: ruby

before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
# Install and configure postgres (a version different from stock). cf
#  - https://stackoverflow.com/questions/55161807/travis-ci-not-connecting-to-postgresql-11-2
#  - https://travis-ci.community/t/postgres-default-port-changed-from-5432-to-5433/7347/7
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12

services:
  - postgresql

bundler_args: --retry 5

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql --version
  - psql -c 'CREATE DATABASE planning_poker_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# /!\ DUPLICATED in docker-compose.yml
addons:
  postgresql: '12.4'

